feat: Added workflow for drift detection.

diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -41,7 +41,8 @@ jobs:
 
             # General ----------------------------------- #
             STACK_NAME: ${{ inputs.stack_name }} # Current stack name used for plan file and artifact naming.
-            RUN_MODE: ${{ inputs.run_mode == 'destroy' && '-destroy' || '' }}
+            RUN_MODE: ${{ inputs.run_mode == 'destroy' && '-destroy' || '' }} # If run_mode is 'destroy', set RUN_MODE to '-destroy' for Terraform plan command.
+            DRIFT_MODE: ${{ inputs.run_mode == 'drift' && '-detailed-exitcode' || '' }} # If run_mode is 'drift', set DRIFT_MODE to '-detailed-exitcode' for Terraform plan command.
 
             # Azure OIDC Authentication  ----------------------------------- #
             ARM_USE_OIDC: true # Force Terraform AzureRM provider to authenticate via OIDC.
@@ -86,11 +87,15 @@ jobs:
               run: terraform validate # Terraform and syntax check.
 
             - name: "Terraform: Plan"
+              id: plan # Assign an ID to this step for referencing outputs.
               timeout-minutes: 10 # Fail this step if it exceeds 'x' minutes.
               env:
                   PLAN_FILE: "${{ inputs.stack_name }}_${{ inputs.run_mode }}.plan"
               run: |
-                  terraform plan ${RUN_MODE} -out=$PLAN_FILE \
+                  set +e
+
+                  terraform plan ${RUN_MODE} ${DRIFT_MODE} \
+                   -out=$PLAN_FILE \
                    -var-file="$TF_VARS_DIR/global.tfvars" \
                    -var-file="$TF_VARS_DIR/$TF_VARS_FILE" \
                    -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
@@ -98,7 +103,26 @@ jobs:
                    -var="remote_state_resource_group=$TF_BACKEND_RG" \
                    -var="remote_state_storage_account=$TF_BACKEND_SA"
 
+                   exitcode=$?
+                   echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+                   
+                   if [ "$exitcode" = "1" ]; then
+                    exit 1
+                   fi
+                   exit 0
+
+            - name: "Drift Detection: Create Issue"
+              # Only run this step if run_mode is 'drift' and Terraform plan detected drift (exit code 2).
+              if: ${{ inputs.run_mode == 'drift' && steps.plan.outputs.exitcode == '2' }}
+              run: |
+                  if [ "${{ steps.plan.outputs.exitcode }}" = "0" ]; then
+                    echo "✅ $STACK_NAME :: No drift detected." >> $GITHUB_STEP_SUMMARY
+                  else
+                    echo "⚠️ $STACK_NAME :: Terraform drift detected." >> $GITHUB_STEP_SUMMARY
+                  fi
+
             - name: "Upload Plan Artifact"
+              if: ${{ inputs.run_mode != 'drift' }}
               uses: actions/upload-artifact@v4 # Upload Terraform plan file produced during the job for use by apply step.
               env:
                   PLAN_FILE: "${{ inputs.stack_name }}_${{ inputs.run_mode }}.plan"
